### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by nightlyone** [pzurek/zed#3]
Please add a license file.

I would like to use this code and contribute the [Zendesk Apps management API](https://developer.zendesk.com/rest_api/docs/core/apps) to it.

Then use both to build a deploying tool for updating Zendesk Apps from a CI like [CircleCI](https://circleci.com/docs/introduction-to-continuous-deployment).

So please consider it.

**Comment by nightlyone** [comment]
ping

**Comment by pzurek** [comment]
Hi Ingo,

Sorry for the lack of response. I've just added the license.
